ISS81 | Implement Postgres support
TheAxelander/OpenBudgeteer pull request #142
Opened 2023-05-09 19:18 UTC by csillaggyujto

Implement Postgres support
Refactor EFCore implementation to migration projects
Prepare separation of concerns
Prepare init container support for k8s

2023-05-09 19:19 UTC, csillaggyujto commented
Fixes #81; #141

2023-05-10 08:53 UTC, TheAxelander commented
First of all many thanks for your contribution here. Please give me some days to have a look into it and run some tests. I will be back at home next week so then I have some more time for it :)

2023-05-18 09:24 UTC, TheAxelander requested changes
I added some comments for things that I observed during some testings. It would be also great if you could add some method documentation for the new stuff in `OpenBudgeteer.Data`.

Again I really appreciate your effort here :)

2023-05-18 09:24 UTC, TheAxelander commented on OpenBudgeteer.Data/MariaDbDatabaseInitializer.cs
> +    [GeneratedRegex("^[a-zA-Z][0-9a-zA-Z$_]{0,63}$", RegexOptions.Compiled | RegexOptions.Singleline)]
Do you see any issues to also add `-` character?

2023-05-18 09:24 UTC, TheAxelander commented on OpenBudgeteer.Data/MariaDbDatabaseInitializer.cs
> +    [GeneratedRegex("^[a-zA-Z][0-9a-zA-Z$_]{0,63}$", RegexOptions.Compiled | RegexOptions.Singleline)]
Just observed that Db names with `-` will fail MySql commands in line 86. Any chance this can be fixed? Otherwise this would need to be marked as a breaking change as this was allowed in the past (I also used it)

2023-05-18 09:24 UTC, TheAxelander commented on OpenBudgeteer.Data/MariaDbDatabaseInitializer.cs
> +        connection.Open();
This will not pass unless `CONNECTION_ROOT_PASSWORD` is set. Can you add a check that this DB and User creation section will be skipped if there is no root password provided, for those people who do this manually and to keep this setting optional

2023-05-18 09:24 UTC, TheAxelander commented on OpenBudgeteer.Data/DbContextOptionsFactory.cs
> +        Path.GetFullPath(dbFilePath);
I think you wanted to have this line here
```
dbFilePath = Path.GetFullPath(dbFilePath);
```

2023-05-18 09:24 UTC, TheAxelander commented on OpenBudgeteer.Data/NoOpDatabaseInitializer.cs
> +        // Do nothing. - SQLite automatically creates the database if not exists
During testing with `"CONNECTION_PROVIDER": "sqlite"` only, the database was not created. Root cause was that the creation only works if the folder `database` in the target path already exists.

2023-05-18 09:24 UTC, TheAxelander commented on OpenBudgeteer.Blazor/Program.cs
>          Host.CreateDefaultBuilder(args)
For `"CONNECTION_PROVIDER": "memory"` I get below exception here:

```
SQLite Error 1: 'no such table: __EFMigrationsHistory'
```

The tables seems to be created without an issue but insert seems to fail:

```
info: 18.05.2023 10:52:53.444 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
info: 18.05.2023 10:52:53.522 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "__EFMigrationsHistory" (
          "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
          "ProductVersion" TEXT NOT NULL
      );
info: 18.05.2023 10:52:53.524 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
```

```
fail: 18.05.2023 10:52:53.587 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command) 
      Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
      VALUES ('20200925091603_InitialCreate', '7.0.5');
```

2023-05-18 09:24 UTC, TheAxelander commented on OpenBudgeteer.Blazor/Program.cs
>          Host.CreateDefaultBuilder(args)
For `"CONNECTION_PROVIDER": "POSTGRES"` I get below exception here:

```
42501: permission denied for schema public
```

DB and User creation was working fine. Below I share my Postgres Docker compose and the config settings:

``` yaml
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
```

``` json
"CONNECTION_PROVIDER": "POSTGRES",
  "CONNECTION_DATABASE": "openbudgeteer_dev",
  "CONNECTION_SERVER": "192.168.178.201",
  "CONNECTION_PORT": "5432",
  "CONNECTION_USER": "openbudgeteer_dev",
  "CONNECTION_PASSWORD": "openbudgeteer_dev",
  "CONNECTION_ROOT_PASSWORD": "example",
```

2023-05-22 17:00 UTC, csillaggyujto commented on OpenBudgeteer.Data/MariaDbDatabaseInitializer.cs
> +    [GeneratedRegex("^[a-zA-Z][0-9a-zA-Z$_]{0,63}$", RegexOptions.Compiled | RegexOptions.Singleline)]
"-" should not be allowed, as it's the start of a comment block in SQL. However, we could make an exception, since - is safe here IF AND ONLY IF ";", "'", """ are not allowed. (SQLi goes something like this: "'; DROP TABLE USERS;--" )

2023-05-23 09:04 UTC, csillaggyujto commented
Thank you for you review, nice catches!
Could you please elaborate on what depth of documentation uou require?
Currently I have a ton if work in my day job, but I will try to look at these bugs somewhere in the next two weeks

2023-05-29 16:40 UTC, csillaggyujto commented
Hi @TheAxelander !

I have completed all the requested changes, and done integration testing with tempdb, MySQL, Postgres and MariaDB.  Please find the tested examples under examples/. (openbudgeteer:alpha is the docker build . on my machine)  The documentation (readme.md) is updated accordingly. Postgres initialization is now done by the postgres container itself. Memory DB feature is nuked.

Should you have time, please review.

2023-05-31 05:37 UTC, TheAxelander commented
Hi @csillaggyujto 

thanks a lot and sorry for the late response, I was a bit out of order the last days. I will have a look on it in the next days.

Just for completeness in regard to documentation:

I was looking for something how it is done in the ViewModels with the structure

``` c#
/// <summary>
/// Lorem ipsum
/// </summary>
/// <param name="lorem">Lorem ipsum</param>
/// <returns>Lorem ipsum</returns>
```

but no worries I can adapt it later on as I noticed that you have already provided some description.

2023-07-01 07:38 UTC, TheAxelander approved these changes

2023-07-01 07:55 UTC, TheAxelander approved these changes

2023-07-01 09:03 UTC, merged